### ISSUE TITLE
yubao_say无法发送图片

### ISSUE THREAD

**Issue by SlightDust** [botyubao/bugtracker#3]
由于跨主机部署，NTQQ从Hoshino传过来的图片路径中读不到图片，考虑改为http获取图片

**Comment by SlightDust** [comment]
> [2023-10-13 21:43:10,967 my_chat] ERROR: <class 'aiocqhttp.exceptions.ActionFailed'> occured when zaine handling message 1207624808.
> [2023-10-13 21:43:10,967 my_chat] ERROR: <ActionFailed status='failed', retcode=-1, msg="ENOENT: no such file or directory, open 'D:\\root\\qqbot\\HoshinoBot\\res\\img\\kyaru\\1.gif'", wording='ws-plugin获取信息失败', echo={'seq': 52}>
> Traceback (most recent call last):
>   File "/root/qqbot/HoshinoBot/hoshino/service.py", line 192, in wrapper
>     return await func(self.bot, ctx)
>   File "/root/qqbot/HoshinoBot/hoshino/modules/my_chat/my_chat.py", line 116, in zaine
>     await bot.send(ev, random.choice(temp_say))
>   File "/usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 271, in send
>     return await self.send_msg(**params)
>   File "/usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 238, in call_action
>     return await self._api.call_action(action=action, **params)
>   File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 178, in call_action
>     result = await self._wsr_api.call_action(action, **params)
>   File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 153, in call_action
>     return _handle_api_result(await
>   File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 38, in _handle_api_result
>     raise ActionFailed(result=result)
> aiocqhttp.exceptions.ActionFailed: <ActionFailed status='failed', retcode=-1, msg="ENOENT: no such file or directory, open 'D:\\root\\qqbot\\HoshinoBot\\res\\img\\kyaru\\1.gif'", wording='ws-plugin获取信息失败', echo={'seq': 52}>

**Comment by SlightDust** [comment]
准确来说是yunzai-ws-plugin从hoshino传来的路径中获取不到图片  
可选解决方案：
 - 改为http获取图片
 - hoshino的img路径同步到yunzai这边

**Comment by SlightDust** [comment]
这个功能使用的是标准R.img()函数。搭建了静态资源服务器，以http形式传图。resolve

**Comment by SlightDust** [comment]
base64无法传送gif格式图片，只能收到第一帧静态图
